[package]
authors = ["Sterling DeMille <sterlingdemille+github@gmail.com>"]
name = "encrusted"
version = "1.1.0"
description = "A z-machine (interpreter) for Infocom-era text adventure games"
repository = "https://github.com/demille/encrusted"
readme = "README.md"
license = "MIT"

[[bin]]
name = "encrusted"
path = "src/main.terminal.rs"

[profile.release]
lto = true
opt-level = 's'

[dependencies]
atty = "0.2.11"
base64 = "0.10.1"
clap = "2.32.0"
enum_primitive = "0.1.1"
lazy_static = "1.2.0"
rand = "0.4.2"
regex = "1.1.0"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_json = "1.0.38"
term_size = "0.3.1"
