[package]
authors = ["Daniel Prilik <danielprilik@gmail.com>", "Sterling DeMille <sterlingdemille+github@gmail.com>"]
name = "encrusted-embedded"
version = "0.1.0"
edition = "2018"
description = "A `no_std` z-machine (interpreter) for Infocom-era text adventure games which runs on _very_ constrained embedded hardware."
repository = "https://github.com/daniel5151/encrusted-embedded"
readme = "README.md"
license = "MIT"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 's'
overflow-checks = false
panic = "abort"
rpath = false

[dependencies]

[workspace]
members = ["encrusted-ui"]
