[package]
authors = ["Sterling DeMille <sterlingdemille+github@gmail.com>"]
name = "encrusted"
version = "1.1.0"
edition = "2018"
description = "A z-machine (interpreter) for Infocom-era text adventure games"
repository = "https://github.com/demille/encrusted"
readme = "README.md"
license = "MIT"

[profile.release]
lto = true
opt-level = 's'

[dependencies]
enum_primitive = "0.1.1"
hashbrown = "0.6.3"

[workspace]
members = ["encrusted-ui"]
