[package]
name = "embcrusted-ui-no-std"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
embcrusted = { path = "../" }
libc = { version = "0.2", default-features = false }
