[package]
name = "term-ui-std"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2.11"
clap = "2.32.0"
encrusted = { path = "../" }
lazy_static = "1.2.0"
rand = "0.4.2"
regex = "1.1.0"
term_size = "0.3.1"
