[package]
name = "encrusted-ui"
version = "0.1.0"
authors = ["Sterling DeMille <sterlingdemille+github@gmail.com>", "Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
encrusted-embedded = { path = "../" }
